-- 코드를 입력하세요
SELECT a.PRODUCT_CODE, SUM(b.SALES_AMOUNT)* a.PRICE AS SALES
from PRODUCT a
INNER JOIN OFFLINE_SALE b ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;
